### ISSUE TITLE
Entrypoints

### ISSUE THREAD

**Issue by dhirschfeld** [althonos/fs.sshfs#20]
I just updated `fs` and I think it blew away `fs.sshfs`??

AFAICS fs.sshfs creates a `sshfs` folder in the `fs` namespace which is never going to work?

I'm confused though because it seems entrypoint support was added over in https://github.com/PyFilesystem/pyfilesystem2/pull/56?

...and there are entrypoints defined in `setup.cfg`
https://github.com/althonos/fs.sshfs/blob/d79362c9bd957985bdb1b67e807192fc05d7e889/setup.cfg#L56-L59

It seems to me that with entrypoints there's no need for `sshfs` to be embedded *within* `fs`?

**Comment by althonos** [comment]
Updating `fs` has no effect on `fs.sshfs`, at least if you're updating with `pip`. I'm having both installed and up-to-date and it works fine. Of course there is no *need* for `fs.sshfs` to be installed within `fs`, but it feels nicer when using the `fs.sshfs` API within Python code rather than using `fs.open_fs`.

I'm also against changing the namespace, because:
* calling the package `sshfs` implies it is an interface to the FUSE `sshfs`, which it is not
* it's a breaking change
* I'd expect a package named `fs.sshfs` to be imported from `fs.sshfs`

**Comment by dhirschfeld** [comment]
I'm using conda but I did some more testing and upgrading *doesn't* blow away an installed `fs.sshfs` so I'm not sure what happened there. I'm still not sure installing a package into anothers namespace is a great idea but since it doesn't break things I'll go ahead and close this.
