### ISSUE TITLE
pypi Version 0.10.1 and pyFilesystem2 version

### ISSUE THREAD

**Issue by ReimarBauer** [althonos/fs.sshfs#25]
Hi

I need some understanding what the `~`Operator in setup.cfg means and why the table of used modules is not showing the needed versions.

The pypi version lists 2.4.0 of PyFilesstem2 :
https://pypi.org/project/fs.sshfs/

it installs 
`fs                        2.3.1`
If 2.4.0 works, can you adopt the value in setup.cfg?

Also some of the other package have updates. pip install fs.sshfs installs on my system:
```
six                                1.12.0 
paramiko                      2.4.2
cached-property           1.5.1 
```

It looks like 
https://pypi.org/project/fs.sshfs/
does not list the  PyFileSystem2 version needed but always the newest available?

regards
Reimar

**Comment by althonos** [comment]
Hi Reimar,

* the versions listed on the front page are always the latest, they are meant to provide a link to the PyPI page of each library rather than the minimum version
* I couldn't provide forward compatibility for `fs` since Pyfilesystem did not follow semantic versioning until `v2.2.0`, but Will confirmed that he'll try to follow it more strictly for future versions, which means I can pin versions as `~=2.2`.
