### ISSUE TITLE
fs.sshfs.SSHFS.download() slower than Paramiko's SFT's get()

### ISSUE THREAD

**Issue by holtgrewe** [althonos/fs.sshfs#26]
When using Paramiko SFTP's `get()`, I'm getting 50MB/s, when using `fs.sshfs.SSHFS.download()` I'm only getting 5MB/s. What could be the reason?

cf #451

**Comment by althonos** [comment]
@holtgrewe : looking at the `paramiko` source it really looks like what they are doing differently is that their buffer size is `32 kB` while the default `fs` chunk size is only `10 kB`. Could you try setting `chunk_size=32768` on your `download` call? If it does the trick I'll update the documentation to advise using a higher buffer size, otherwise I'll patch `SSHFS.download` to use `SFTP.getfo`.

**Comment by holtgrewe** [comment]
Hi. No, still getting <5MB/s

**Comment by althonos** [comment]
Found it, turns out Paramiko is using a background thread to prefetch data when reading a remote file that is not enable by default. I have enabled it and indeed got a 8x to 12x speed increase. I'll release a new version with this patch.

**Comment by holtgrewe** [comment]
Excellent news: :+1:

**Comment by althonos** [comment]
Fixed in release `v0.11.0`.
