### ISSUE TITLE
Improving the throughput of scandir

### ISSUE THREAD

**Issue by jwnimmer-tri** [althonos/fs.sshfs#36]
The current implementation of fs.sshfs only overrides `listdir` and not `scandir`, and so inherits the FS base class' default implementation of `scandir`. That implementation does a `getinfo` on every item in the directory, which ends up with an `lstat` via sshfs.  That incurs a network round-trip for each file in the directory.  That O(n) penalty can really add up, especially for operations that need the size or modification time details, such as `copy` or `mirror`.

However, the sftp protocol allows us to stat as part of the list operation all in one go, so sshfs could override `scandir` to take advantage of that optimization and minimize round-trips.

Locally, I have monkey-patched sshfs to use this optimization (see code below).  I wonder if we could incorporate a version of this patch into fs.sshfs directly?

```python
def _sshfs_scandir(self, path, namespaces=None, page=None):
    _namespaces = namespaces or ()
    _start, _end = (page or (0, None))
    _path = self.validatepath(path)
    _type = self.gettype(_path)
    if _type is not fs.enums.ResourceType.directory:
        raise fs.errors.DirectoryExpected(path)
    with fs.sshfs.error_tools.convert_sshfs_errors('scandir', path):
        for i, _stat_result in enumerate(self._sftp.listdir_attr(_path)):
            if i < _start:
                continue
            if _end is not None and i >= _end:
                break
            _name = _stat_result.filename
            yield self._make_info(_name, _stat_result, _namespaces)
```

Note that here I still have a `gettype` call in the critical path.  I believe we could remove that as well, with some careful exception handling in the with block, to make sure we get DirectoryExepected in case of a bad path.

**Comment by althonos** [comment]
@jwnimmer-tri : I'd be happy to integrate your patch! Could you open a PR so that we can both work on editing the code?

I also think the code you proposed can be improved in two different places:

- [ ] You can use `itertools.islice` instead of `enumerate` to easily read only a slice of the iterator, instead of checking with enumerate, then your loop would be only 2 lines long with one less variable.
- [ ] You should use `listdir_iter` instead of `listdir_attr` here, otherwise you're defeating the purpose of `scandir` as an iterator.

> Note that here I still have a gettype call in the critical path. I believe we could remove that as well, with some careful exception handling in the with block, to make sure we get DirectoryExepected in case of a bad path.

The `gettype` does two things, checking the path exist, and that is it a directory, which are two different errors in PyFilesystem but the same error with `paramiko`. But that could be factored out by differentiating between the cases *only* when an error `FileNotFoundError` is raised.

**Comment by jwnimmer-tri** [comment]
Thanks, good points.  Let me play with my monkey patch a bit more until I like it, and then I'll open a PR.
